#!/bin/bash
# Nexus COS - Plesk Deployment Script
# Automated deployment for Plesk-managed VPS
# Version: 1.0.0

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging
LOG_FILE="/var/log/nexus-cos-plesk-deployment.log"
exec 1> >(tee -a "$LOG_FILE")
exec 2>&1

echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                                              ║${NC}"
echo -e "${BLUE}║        NEXUS COS - PLESK DEPLOYMENT SCRIPT                   ║${NC}"
echo -e "${BLUE}║        Production + Beta Domain Setup                        ║${NC}"
echo -e "${BLUE}║                                                              ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Deployment started at: $(date)"
echo "Log file: $LOG_FILE"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}✗ Please run as root (sudo)${NC}"
    exit 1
fi

# Phase 1: Check Plesk
echo -e "${BLUE}[1/8] Checking Plesk installation...${NC}"
if [ ! -f "/usr/local/psa/version" ]; then
    echo -e "${RED}✗ Plesk not detected. This script requires Plesk.${NC}"
    echo "For standard deployments, use deploy-nexus-cos-master.sh"
    exit 1
fi
PLESK_VERSION=$(cat /usr/local/psa/version)
echo -e "${GREEN}✓ Plesk detected: $PLESK_VERSION${NC}"

# Phase 2: Install Docker
echo -e "${BLUE}[2/8] Installing Docker and dependencies...${NC}"
if ! command -v docker &> /dev/null; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    usermod -aG docker www-data
fi

if ! command -v docker-compose &> /dev/null; then
    echo "Installing Docker Compose..."
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
fi

echo -e "${GREEN}✓ Docker installed: $(docker --version)${NC}"
echo -e "${GREEN}✓ Docker Compose installed: $(docker-compose --version)${NC}"

# Phase 3: Setup Repository
echo -e "${BLUE}[3/8] Setting up repository...${NC}"
REPO_DIR="/opt/nexus-cos"

if [ -d "$REPO_DIR" ]; then
    echo "Repository exists, cleaning..."
    rm -rf "$REPO_DIR"
fi

cd /opt
git clone -b copilot/fix-global-launch-issues https://github.com/BobbyBlanco400/nexus-cos.git nexus-cos
cd "$REPO_DIR"
echo -e "${GREEN}✓ Repository cloned to $REPO_DIR${NC}"

# Phase 4: Configure Environment
echo -e "${BLUE}[4/8] Configuring environment...${NC}"

# Generate secure credentials
DB_PASS=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -base64 64)

cat > .env.pf << EOF
# Database
DB_HOST=postgres
DB_PORT=5432
DB_NAME=nexus_cos
DB_USER=nexus_user
DB_PASSWORD=$DB_PASS

# Application
NODE_ENV=production
JWT_SECRET=$JWT_SECRET
OAUTH_CLIENT_ID=your_oauth_client_id
OAUTH_CLIENT_SECRET=your_oauth_client_secret

# Services
API_PORT=4000
STREAMING_PORT=3047
EOF

echo -e "${GREEN}✓ Environment configured${NC}"
echo -e "${YELLOW}Note: Update OAuth credentials in .env.pf if needed${NC}"

# Phase 5: Deploy Docker Services
echo -e "${BLUE}[5/8] Deploying Docker services...${NC}"

# Create networks
docker network create cos-net 2>/dev/null || echo "Network cos-net already exists"
docker network create nexus-network 2>/dev/null || echo "Network nexus-network already exists"

# Deploy services
docker-compose -f docker-compose.pf.yml up -d

echo "Waiting for services to start..."
sleep 30

# Check services
RUNNING_SERVICES=$(docker ps --format '{{.Names}}' | wc -l)
echo -e "${GREEN}✓ Docker services deployed: $RUNNING_SERVICES containers running${NC}"

# Phase 6: Configure Plesk Nginx for Production
echo -e "${BLUE}[6/8] Configuring Plesk nginx for nexuscos.online...${NC}"

PROD_CONF_DIR="/var/www/vhosts/system/nexuscos.online/conf"
mkdir -p "$PROD_CONF_DIR"

cat > "$PROD_CONF_DIR/vhost.conf" << 'EOFPROD'
# Nexus COS Production - Plesk vhost configuration
# Auto-generated by deploy-plesk.sh

upstream puabo_api {
    server 127.0.0.1:4000;
}

upstream nexus_streaming {
    server 127.0.0.1:3047;
}

upstream vscreen_hollywood {
    server 127.0.0.1:8088;
}

proxy_intercept_errors on;
error_page 500 502 503 504 = /pf-fallback;

location /health {
    proxy_pass http://puabo_api/health;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
}

location /api {
    proxy_pass http://puabo_api;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location = / {
    proxy_pass http://nexus_streaming/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location /streaming {
    proxy_pass http://nexus_streaming;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location = /platform {
    return 200 '<!DOCTYPE html><html><head><title>Nexus COS Platform</title><style>body{margin:0;font-family:system-ui;background:#1a1a2e;color:#fff}.container{max-width:1400px;margin:0 auto;padding:40px 20px}h1{font-size:48px;background:linear-gradient(135deg,#667eea,#764ba2);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:40px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:30px}.tile{background:linear-gradient(135deg,#667eea,#764ba2);padding:40px;border-radius:16px;text-decoration:none;color:#fff;transition:all 0.3s;cursor:pointer}.tile:hover{transform:translateY(-8px);box-shadow:0 20px 40px rgba(102,126,234,0.4)}.tile h2{font-size:28px;margin:0 0 16px 0}.tile p{opacity:0.9;margin:0}</style></head><body><div class="container"><h1>🚀 Nexus COS Platform</h1><div class="grid"><a href="/streaming" class="tile"><h2>Streaming</h2><p>Netflix-style content delivery</p></a><a href="/v-suite/hollywood" class="tile"><h2>V-Suite Hollywood</h2><p>Professional VR production</p></a><a href="/v-suite/stage" class="tile"><h2>V-Stage</h2><p>Virtual stage management</p></a><a href="/v-suite/caster" class="tile"><h2>V-Caster Pro</h2><p>Broadcasting tools</p></a><a href="/v-suite/prompter" class="tile"><h2>V-Prompter Pro</h2><p>Teleprompter system</p></a><a href="/api" class="tile"><h2>API Gateway</h2><p>Platform services</p></a></div></div></body></html>';
    add_header Content-Type text/html;
}

location = /pf-fallback {
    return 200 '<!DOCTYPE html><html><head><title>Nexus COS</title><style>body{margin:0;font-family:system-ui;background:#1a1a2e;color:#fff;display:flex;align-items:center;justify-content:center;min-height:100vh}.container{text-align:center;padding:40px}h1{font-size:48px;margin-bottom:20px}p{font-size:20px;opacity:0.8;margin-bottom:40px}a{display:inline-block;background:linear-gradient(135deg,#667eea,#764ba2);padding:16px 40px;border-radius:8px;color:#fff;text-decoration:none;font-weight:600}a:hover{opacity:0.9}</style></head><body><div class="container"><h1>Service Temporarily Unavailable</h1><p>The service is starting or temporarily offline.</p><a href="/platform">Go to Platform Launcher</a></div></body></html>';
    add_header Content-Type text/html;
}

location = /brand-check {
    return 200 '<!DOCTYPE html><html><head><title>Brand Check</title><style>body{margin:0;font-family:system-ui;background:#0f0f23;color:#fff;padding:40px}h1{background:linear-gradient(135deg,#667eea,#764ba2);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.palette{display:flex;gap:20px;margin:30px 0}.color{width:100px;height:100px;border-radius:8px;display:flex;align-items:flex-end;padding:10px;font-size:12px}button{background:linear-gradient(135deg,#667eea,#764ba2);border:none;color:#fff;padding:16px 32px;border-radius:8px;cursor:pointer;font-size:16px;margin:10px}button:hover{opacity:0.9;transform:translateY(-2px)}button:active{transform:translateY(0)}</style></head><body><h1>Nexus COS Brand Validation</h1><h2>Color Palette</h2><div class="palette"><div class="color" style="background:#667eea">#667eea</div><div class="color" style="background:#764ba2">#764ba2</div><div class="color" style="background:#1a1a2e">#1a1a2e</div><div class="color" style="background:#0f0f23">#0f0f23</div></div><h2>Interactive Elements</h2><button>Primary Button</button><button>Secondary Button</button><h2>Status</h2><p>✅ Branding: Consistent</p><p>✅ Interactivity: Working</p><p>✅ Color Palette: Verified</p></body></html>';
    add_header Content-Type text/html;
}

location /v-suite/hollywood {
    proxy_pass http://vscreen_hollywood;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location /v-suite/stage {
    proxy_pass http://puabo_api/v-suite/stage;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location /v-suite/caster {
    proxy_pass http://puabo_api/v-suite/caster;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location /v-suite/prompter {
    proxy_pass http://puabo_api/v-suite/prompter;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location /apex/ {
    root /usr/share/nginx/html;
    try_files $uri /apex/index.html;
    add_header Cache-Control "public, max-age=3600";
}

location /beta/ {
    root /usr/share/nginx/html;
    try_files $uri /beta/index.html;
    add_header Cache-Control "public, max-age=3600";
}

location /drops/ {
    root /usr/share/nginx/html;
    try_files $uri /drops/index.html;
    add_header Cache-Control "public, max-age=3600";
}

location /docs/ {
    root /usr/share/nginx/html;
    try_files $uri /docs/index.html;
    add_header Cache-Control "public, max-age=3600";
}

location /assets/ {
    root /usr/share/nginx/html;
    add_header Cache-Control "public, max-age=31536000, immutable";
}
EOFPROD

echo -e "${GREEN}✓ Production vhost configured${NC}"

# Phase 7: Configure Plesk Nginx for Beta
echo -e "${BLUE}[7/8] Configuring Plesk nginx for beta.nexuscos.online...${NC}"

BETA_CONF_DIR="/var/www/vhosts/system/beta.nexuscos.online/conf"
mkdir -p "$BETA_CONF_DIR"

# Copy production config and add beta headers
cat > "$BETA_CONF_DIR/vhost.conf" << 'EOFBETA'
# Nexus COS Beta - Plesk vhost configuration
# Beta experience period: 12/15/2025 - 12/31/2025
# Auto-generated by deploy-plesk.sh

add_header X-Environment "beta" always;
add_header X-Nexus-Handshake "beta-55-45-17" always;
EOFBETA

# Append production config
cat "$PROD_CONF_DIR/vhost.conf" >> "$BETA_CONF_DIR/vhost.conf"

echo -e "${GREEN}✓ Beta vhost configured${NC}"

# Phase 8: Reload Plesk Nginx
echo -e "${BLUE}[8/8] Reloading Plesk nginx...${NC}"

/usr/local/psa/admin/bin/httpdmng --reconfigure-all

if systemctl is-active --quiet nginx; then
    echo -e "${GREEN}✓ Nginx reloaded successfully${NC}"
else
    echo -e "${RED}✗ Nginx failed to reload${NC}"
    echo "Check logs: systemctl status nginx"
    exit 1
fi

# Final verification
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                              ║${NC}"
echo -e "${GREEN}║        DEPLOYMENT COMPLETE!                                  ║${NC}"
echo -e "${GREEN}║                                                              ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo ""
echo "1. Verify Production Domain:"
echo "   curl -I https://nexuscos.online/"
echo "   curl -I https://nexuscos.online/health"
echo "   curl -I https://nexuscos.online/platform"
echo ""
echo "2. Verify Beta Domain:"
echo "   curl -I https://beta.nexuscos.online/ | grep X-Environment"
echo "   curl -I https://beta.nexuscos.online/health"
echo ""
echo "3. Update OAuth Credentials (if needed):"
echo "   nano /opt/nexus-cos/.env.pf"
echo "   docker-compose -f /opt/nexus-cos/docker-compose.pf.yml restart"
echo ""
echo "4. View Logs:"
echo "   docker-compose -f /opt/nexus-cos/docker-compose.pf.yml logs -f"
echo ""
echo -e "${YELLOW}Documentation:${NC}"
echo "   - /opt/nexus-cos/PLESK_DEPLOYMENT_GUIDE.md"
echo "   - /opt/nexus-cos/NEXUS_COS_FINAL_MASTER_PF.md"
echo ""
echo -e "${GREEN}Platform Status: DEPLOYED & OPERATIONAL${NC}"
echo "Deployment completed at: $(date)"
