// PM2 Ecosystem Configuration for Nexus COS
// Generated by GitHub Copilot Code Agent PF Review & Fix Script

module.exports = {
  apps: [
    {
      name: 'auth',
      script: './services/auth-service/server.js',
      cwd: '/home/runner/work/nexus-cos/nexus-cos',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3100
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3100
      },
      log_file: './logs/auth.log',
      out_file: './logs/auth-out.log',
      error_file: './logs/auth-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    },
    {
      name: 'billing',
      script: './services/billing-service/server.js',
      cwd: '/home/runner/work/nexus-cos/nexus-cos',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3110
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3110
      },
      log_file: './logs/billing.log',
      out_file: './logs/billing-out.log',
      error_file: './logs/billing-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
    }
  ]
};