# NEXUS COS Global Launch Infrastructure Configuration
# System Metadata and Multi-Phase Deployment Configuration

project:
  name: "NEXUS COS"
  version: "1.0.0"
  status: "READY_FOR_LAUNCH"
  priority: "CRITICAL"
  review_type: "AI_AGENT"

launch_phases:
  beta:
    domain: "beta.n3xuscos.online"
    start_date: "2025-10-01T00:00:00Z"
    environment: "beta"
    ssl:
      provider: "IONOS"
      cert_path: "/etc/ssl/ionos/beta.n3xuscos.online/"
      protocols: ["TLSv1.2", "TLSv1.3"]
      ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
    cdn:
      provider: "CloudFlare"
      mode: "Full (Strict)"
      edge_locations: "global"
    security:
      hsts_max_age: 31536000
      csp: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
      frame_options: "SAMEORIGIN"
    logging:
      access_log: "/var/log/nginx/beta.n3xuscos.online_access.log"
      error_log: "/var/log/nginx/beta.n3xuscos.online_error.log"
      level: "warn"
    features:
      - "basic_ssl"
      - "gzip_compression"
      - "security_headers"
      - "cdn_integration"
      
  production:
    domain: "n3xuscos.online"
    transition_date: "2025-11-17T00:00:00Z"
    environment: "production"
    ssl:
      provider: "IONOS"
      cert_path: "/etc/ssl/ionos/n3xuscos.online/"
      protocols: ["TLSv1.2", "TLSv1.3"]
      ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
      session_cache: "shared:SSL:50m"
      session_timeout: "1d"
      session_tickets: false
      buffer_size: "4k"
    cdn:
      provider: "CloudFlare"
      mode: "Full (Strict)"
      edge_locations: "global"
    security:
      hsts_max_age: 63072000
      csp: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"
      frame_options: "SAMEORIGIN"
      rate_limiting:
        api_zone: "10m"
        api_rate: "10r/s"
        login_zone: "10m"
        login_rate: "1r/s"
    logging:
      access_log: "/var/log/nginx/n3xuscos.online_access.log"
      error_log: "/var/log/nginx/n3xuscos.online_error.log"
      level: "warn"
    features:
      - "enhanced_ssl"
      - "advanced_gzip_compression"
      - "enhanced_security_headers"
      - "rate_limiting"
      - "ip_restrictions"
      - "cdn_integration"
      - "production_monitoring"

# Service Configuration
services:
  backend_node:
    port: 3000
    health_endpoint: "/health"
    api_prefix: "/api/"
    
  backend_python:
    port: 3001
    health_endpoint: "/health"
    api_prefix: "/py/"
    
  v_suite:
    port: 3010
    api_prefix: "/v-suite/"
    
  creator_hub:
    port: 3020
    api_prefix: "/creator-hub/"
    upload_limit: "100M" # Beta
    upload_limit_production: "200M" # Production
    
  puaboverse:
    port: 3030
    api_prefix: "/puaboverse/"
    
  monitoring:
    grafana_port: 3003
    prometheus_port: 9090
    restrictions:
      beta: false
      production: true
      allowed_networks:
        - "192.168.0.0/16"
        - "10.0.0.0/8"

# Deployment Configuration
deployment:
  strategy: "phase_aware"
  health_checks: true
  rollback_on_failure: true
  
  pre_deployment_checks:
    - "ssl_certificate_validation"
    - "dns_resolution"
    - "service_connectivity"
    - "database_connectivity"
    
  post_deployment_checks:
    - "health_endpoint_verification"
    - "ssl_grade_verification"
    - "cdn_detection"
    - "performance_metrics"

# Monitoring and Alerting
monitoring:
  health_checks:
    interval: "30s"
    timeout: "10s"
    retries: 3
    
  metrics:
    - "response_time"
    - "error_rate"
    - "ssl_certificate_expiry"
    - "cdn_cache_hit_ratio"
    - "active_connections"
    
  alerting:
    channels:
      - "email"
      - "slack"
    thresholds:
      response_time_ms: 2000
      error_rate_percent: 5
      ssl_expiry_days: 30

# Automation Scripts
automation:
  phase_detection: "nexus-cos-global-launch.sh"
  verification: "nexus-cos-pf-master.js"
  health_check: "health-check-pf-v1.2.sh"
  
  scheduled_tasks:
    ssl_renewal:
      frequency: "weekly"
      command: "certbot renew --nginx"
    log_rotation:
      frequency: "daily"
      retention: "30d"
    backup:
      frequency: "daily"
      retention: "7d"

# Environment Variables
environment_variables:
  beta:
    NODE_ENV: "beta"
    DOMAIN: "beta.n3xuscos.online"
    SSL_PROVIDER: "IONOS"
    CDN_PROVIDER: "CloudFlare"
    LOG_LEVEL: "info"
    
  production:
    NODE_ENV: "production"
    DOMAIN: "n3xuscos.online"
    SSL_PROVIDER: "IONOS"
    CDN_PROVIDER: "CloudFlare"
    LOG_LEVEL: "warn"
    ENABLE_RATE_LIMITING: "true"
    ENABLE_IP_RESTRICTIONS: "true"

# Resource Limits
resources:
  beta:
    max_connections: 1000
    worker_processes: 2
    client_max_body_size: "100M"
    
  production:
    max_connections: 5000
    worker_processes: "auto"
    client_max_body_size: "200M"
    buffer_size: "4k"
    
# Backup and Recovery
backup:
  frequency: "daily"
  retention: "30d"
  destinations:
    - "local:/backup/nexus-cos"
    - "cloud:s3://nexus-cos-backups"
    
recovery:
  rto: "4h" # Recovery Time Objective
  rpo: "1h" # Recovery Point Objective
  procedures:
    - "database_restore"
    - "application_rollback"
    - "dns_failover"