version: "3.9"
services:
  api:
    build: .
    container_name: puabo-api
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"   # change host side if conflict (e.g., "3005:3000")
    restart: unless-stopped
