#!/bin/bash
# ==============================================================================
# Nexus COS Plesk Apache Configuration Setup Script
# Purpose: Set up Apache proxy configuration for Plesk-managed servers
# Usage: ./setup-plesk-apache.sh [domain]
# ==============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DOMAIN="${1:-nexuscos.online}"
PLESK_VHOST_DIR="/var/www/vhosts/${DOMAIN}/conf"
APACHE_CONF_FILE="${PLESK_VHOST_DIR}/vhost_nginx.conf"

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# Enable required Apache modules
enable_apache_modules() {
    log_info "Enabling required Apache modules..."
    
    local modules=("proxy" "proxy_http" "proxy_wstunnel" "rewrite" "headers")
    
    for mod in "${modules[@]}"; do
        if ! a2query -m "$mod" &>/dev/null; then
            a2enmod "$mod"
            log_success "Enabled module: $mod"
        else
            log_info "Module already enabled: $mod"
        fi
    done
}

# Create Apache vhost configuration
create_vhost_config() {
    log_info "Creating Apache vhost configuration for ${DOMAIN}..."
    
    # Ensure directory exists
    mkdir -p "${PLESK_VHOST_DIR}"
    
    # Create the configuration file
    cat > "${APACHE_CONF_FILE}" << 'EOF'
# ==============================================================================
# Nexus COS Apache Proxy Configuration
# Auto-generated by setup-plesk-apache.sh
# ==============================================================================

# Enable required modules
<IfModule mod_proxy.c>
    ProxyRequests Off
    ProxyPreserveHost On
    
    # Main API endpoint
    ProxyPass /api/ http://127.0.0.1:3001/ retry=0
    ProxyPassReverse /api/ http://127.0.0.1:3001/
    
    # Health endpoint
    ProxyPass /health http://127.0.0.1:3001/health retry=0
    ProxyPassReverse /health http://127.0.0.1:3001/health
    
    # API Health endpoint
    ProxyPass /api/health http://127.0.0.1:4000/health retry=0
    ProxyPassReverse /api/health http://127.0.0.1:4000/health
    
    # Root Socket.IO endpoint
    ProxyPass /socket.io/ http://127.0.0.1:3001/socket.io/ retry=0
    ProxyPassReverse /socket.io/ http://127.0.0.1:3001/socket.io/
    
    # Streaming Socket.IO endpoint
    ProxyPass /streaming/socket.io/ http://127.0.0.1:3001/socket.io/ retry=0
    ProxyPassReverse /streaming/socket.io/ http://127.0.0.1:3001/socket.io/
    
    # Streaming Service
    ProxyPass /streaming/ http://127.0.0.1:3001/streaming/ retry=0
    ProxyPassReverse /streaming/ http://127.0.0.1:3001/streaming/
    
    # Creator Hub Service
    ProxyPass /creator/ http://127.0.0.1:3020/ retry=0
    ProxyPassReverse /creator/ http://127.0.0.1:3020/
    
    ProxyPass /creator-hub/ http://127.0.0.1:3020/ retry=0
    ProxyPassReverse /creator-hub/ http://127.0.0.1:3020/
    
    # V-Suite Services
    ProxyPass /v-suite/ http://127.0.0.1:3010/ retry=0
    ProxyPassReverse /v-suite/ http://127.0.0.1:3010/
    
    # AI Service
    ProxyPass /ai/ http://127.0.0.1:3010/ retry=0
    ProxyPassReverse /ai/ http://127.0.0.1:3010/
    
    # Keys Service
    ProxyPass /keys/ http://127.0.0.1:3014/ retry=0
    ProxyPassReverse /keys/ http://127.0.0.1:3014/
    
    # PuaboVerse Module
    ProxyPass /puaboverse/ http://127.0.0.1:3030/ retry=0
    ProxyPassReverse /puaboverse/ http://127.0.0.1:3030/
    
    # Gateway Health
    ProxyPass /health/gateway http://127.0.0.1:4000/health retry=0
    ProxyPassReverse /health/gateway http://127.0.0.1:4000/health
    
    # PUABO NEXUS Fleet Services
    ProxyPass /puabo-nexus/dispatch http://127.0.0.1:9001 retry=0
    ProxyPassReverse /puabo-nexus/dispatch http://127.0.0.1:9001
    
    ProxyPass /puabo-nexus/driver http://127.0.0.1:9002 retry=0
    ProxyPassReverse /puabo-nexus/driver http://127.0.0.1:9002
    
    ProxyPass /puabo-nexus/fleet http://127.0.0.1:9003 retry=0
    ProxyPassReverse /puabo-nexus/fleet http://127.0.0.1:9003
    
    ProxyPass /puabo-nexus/routes http://127.0.0.1:9004 retry=0
    ProxyPassReverse /puabo-nexus/routes http://127.0.0.1:9004
    
    # Increase timeout for WebSocket connections
    ProxyTimeout 86400
</IfModule>

# WebSocket Support
<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # Root Socket.IO WebSocket upgrade
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /socket.io/(.*) ws://127.0.0.1:3001/socket.io/$1 [P,L]
    
    # Streaming Socket.IO WebSocket upgrade
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /streaming/socket.io/(.*) ws://127.0.0.1:3001/socket.io/$1 [P,L]
</IfModule>

# Security Headers
<IfModule mod_headers.c>
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set Referrer-Policy "no-referrer-when-downgrade"
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
</IfModule>
EOF

    log_success "Created Apache configuration at ${APACHE_CONF_FILE}"
}

# Restart Apache
restart_apache() {
    log_info "Restarting Apache..."
    
    if command -v plesk &>/dev/null; then
        plesk repair web -y
        log_success "Plesk web service repaired"
    else
        systemctl restart apache2 || systemctl restart httpd
        log_success "Apache restarted"
    fi
}

# Validate configuration
validate_config() {
    log_info "Validating Apache configuration..."
    
    if apachectl configtest 2>&1; then
        log_success "Apache configuration is valid"
    else
        log_error "Apache configuration validation failed"
        exit 1
    fi
}

# Test endpoints
test_endpoints() {
    log_info "Testing endpoints..."
    
    local endpoints=(
        "https://${DOMAIN}/"
        "https://${DOMAIN}/api/health"
        "https://${DOMAIN}/socket.io/?EIO=4&transport=polling"
        "https://${DOMAIN}/streaming/socket.io/?EIO=4&transport=polling"
    )
    
    for url in "${endpoints[@]}"; do
        echo -e "=== ${url} ==="
        local status=$(curl -sS -o /dev/null -w "%{http_code}\n" --max-time 10 "${url}" 2>/dev/null || echo "FAILED")
        if [[ "$status" == "200" ]] || [[ "$status" == "0" ]]; then
            log_success "Status: ${status}"
        else
            log_warning "Status: ${status}"
        fi
    done
}

# Main execution
main() {
    echo "=================================================="
    echo " Nexus COS Plesk Apache Configuration Setup"
    echo " Domain: ${DOMAIN}"
    echo "=================================================="
    echo ""
    
    check_root
    enable_apache_modules
    create_vhost_config
    validate_config
    restart_apache
    
    echo ""
    log_success "Setup complete!"
    echo ""
    log_info "Testing endpoints..."
    test_endpoints
    
    echo ""
    echo "=================================================="
    echo " Next Steps:"
    echo "=================================================="
    echo " 1. Verify all services are running (PM2, Node.js, etc.)"
    echo " 2. Test WebSocket connections in your application"
    echo " 3. Check logs if any endpoint returns errors:"
    echo "    - /var/log/apache2/error.log"
    echo "    - /var/log/apache2/access.log"
    echo "=================================================="
}

# Run main function
main "$@"
