name: Deploy Nexus COS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install RNPM globally
        run: npm install -g rnpm

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Mobile Dependencies
        run: |
          cd mobile
          npm install
          rnpm link
