#!/bin/bash
# ==============================================================================
# Nexus COS - PF Fix Nginx Headers & Redirect
# ==============================================================================
# Purpose: Fix Nginx security headers and HTTP→HTTPS redirect configuration
# Target: Works with last 3 PF deployments
# Usage: sudo bash scripts/pf-fix-nginx-headers-redirect.sh
#        sudo DOMAIN=yourdomain.com bash scripts/pf-fix-nginx-headers-redirect.sh
# ==============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Configuration
DOMAIN="${DOMAIN:-nexuscos.online}"
NGINX_CONF_DIR="/etc/nginx"
NGINX_MAIN_CONF="${NGINX_CONF_DIR}/nginx.conf"
SECURITY_HEADERS_CONF="${NGINX_CONF_DIR}/conf.d/zz-security-headers.conf"

# ==============================================================================
# Utility Functions
# ==============================================================================

print_header() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                                                                ║${NC}"
    echo -e "${CYAN}║       NEXUS COS - PF FIX NGINX HEADERS & REDIRECT              ║${NC}"
    echo -e "${CYAN}║                                                                ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_section() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
}

print_step() {
    echo -e "${YELLOW}▶${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${CYAN}ℹ${NC} $1"
}

# ==============================================================================
# 1. Verify Root Privileges
# ==============================================================================

verify_root() {
    print_section "1. VERIFY ROOT PRIVILEGES"
    
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root or with sudo"
        echo -e "${YELLOW}Usage:${NC} sudo bash scripts/pf-fix-nginx-headers-redirect.sh"
        exit 1
    fi
    
    print_success "Running with root privileges"
    print_info "Target domain: ${DOMAIN}"
}

# ==============================================================================
# 2. Create Security Headers Configuration
# ==============================================================================

create_security_headers() {
    print_section "2. CREATE SECURITY HEADERS CONFIGURATION"
    
    print_step "Creating conf.d directory if needed..."
    mkdir -p "${NGINX_CONF_DIR}/conf.d"
    print_success "conf.d directory ready"
    
    print_step "Writing security headers to ${SECURITY_HEADERS_CONF}..."
    
    cat > "${SECURITY_HEADERS_CONF}" << 'EOF'
# Nexus COS Security Headers
# Generated by pf-fix-nginx-headers-redirect.sh

# HSTS (HTTP Strict Transport Security)
# Force browsers to use HTTPS for 1 year
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

# Content Security Policy
# Note: Configured for broad compatibility with dynamic web applications
# Adjust based on your specific application requirements
add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'" always;

# X-Content-Type-Options
# Prevent MIME type sniffing
add_header X-Content-Type-Options "nosniff" always;

# X-Frame-Options
# Prevent clickjacking attacks
add_header X-Frame-Options "SAMEORIGIN" always;

# Referrer-Policy
# Control referrer information sent with requests
add_header Referrer-Policy "no-referrer-when-downgrade" always;

# X-XSS-Protection (Legacy, but some browsers still use it)
add_header X-XSS-Protection "1; mode=block" always;
EOF
    
    print_success "Security headers written to ${SECURITY_HEADERS_CONF}"
}

# ==============================================================================
# 3. Ensure conf.d/*.conf Inclusion in nginx.conf
# ==============================================================================

ensure_confd_inclusion() {
    print_section "3. ENSURE CONF.D INCLUSION IN NGINX.CONF"
    
    print_step "Checking if conf.d/*.conf is included in nginx.conf..."
    
    if grep -q "include[[:space:]]*${NGINX_CONF_DIR}/conf.d/.*\.conf" "${NGINX_MAIN_CONF}"; then
        print_success "conf.d/*.conf inclusion already present"
        return 0
    fi
    
    print_warning "conf.d/*.conf inclusion not found, adding it..."
    
    # Backup nginx.conf
    BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    cp "${NGINX_MAIN_CONF}" "${NGINX_MAIN_CONF}.backup.${BACKUP_TIMESTAMP}"
    print_info "Backup created: ${NGINX_MAIN_CONF}.backup.${BACKUP_TIMESTAMP}"
    
    # Find the http block and add the include directive
    # We'll add it right after the opening of the http block
    if grep -q "^http[[:space:]]*{" "${NGINX_MAIN_CONF}"; then
        # Add include directive after http { line
        sed -i '/^http[[:space:]]*{/a \    include '"${NGINX_CONF_DIR}"'/conf.d/*.conf;' "${NGINX_MAIN_CONF}"
        print_success "Added conf.d/*.conf inclusion to nginx.conf"
    else
        print_error "Could not find 'http {' block in nginx.conf"
        print_warning "Please manually add: include ${NGINX_CONF_DIR}/conf.d/*.conf; inside the http block"
    fi
}

# ==============================================================================
# 4. Fix HTTP→HTTPS Redirect
# ==============================================================================

fix_https_redirect() {
    print_section "4. FIX HTTP→HTTPS REDIRECT"
    
    print_step "Finding active vhost configuration..."
    
    # Get the active vhost file using nginx -T
    ACTIVE_VHOST=$(nginx -T 2>/dev/null | grep -B 5 "listen.*80" | grep "# configuration file:" | head -1 | awk '{print $4}')
    
    if [[ -z "$ACTIVE_VHOST" ]]; then
        print_warning "Could not detect active vhost via nginx -T, searching manually..."
        
        # Search common locations
        for conf_file in \
            "${NGINX_CONF_DIR}/sites-enabled/default" \
            "${NGINX_CONF_DIR}/sites-enabled/nexuscos" \
            "${NGINX_CONF_DIR}/sites-available/default" \
            "${NGINX_CONF_DIR}/sites-available/nexuscos" \
            "${NGINX_CONF_DIR}/conf.d/default.conf" \
            "${NGINX_CONF_DIR}/conf.d/nexus-cos.conf"; do
            
            if [[ -f "$conf_file" ]] && grep -q "listen.*80" "$conf_file"; then
                ACTIVE_VHOST="$conf_file"
                break
            fi
        done
    fi
    
    if [[ -z "$ACTIVE_VHOST" ]]; then
        print_error "Could not find active vhost configuration"
        print_warning "Please manually update your Nginx vhost to use: return 301 https://${DOMAIN}\$request_uri;"
        return 1
    fi
    
    print_success "Found vhost: ${ACTIVE_VHOST}"
    
    # Backup the vhost file
    BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    cp "${ACTIVE_VHOST}" "${ACTIVE_VHOST}.backup.${BACKUP_TIMESTAMP}"
    print_info "Backup created: ${ACTIVE_VHOST}.backup.${BACKUP_TIMESTAMP}"
    
    print_step "Fixing redirect pattern in ${ACTIVE_VHOST}..."
    
    # Replace various redirect patterns with the correct one
    # Pattern 1: return 301 https://$server_name$request_uri;
    # Pattern 2: return 301 https://$host$request_uri;
    # Pattern 3: return 301 https://;
    # All become: return 301 https://nexuscos.online$request_uri;
    
    sed -i "s|return[[:space:]]*301[[:space:]]*https://\$server_name\$request_uri;|return 301 https://${DOMAIN}\$request_uri;|g" "${ACTIVE_VHOST}"
    sed -i "s|return[[:space:]]*301[[:space:]]*https://\$host\$request_uri;|return 301 https://${DOMAIN}\$request_uri;|g" "${ACTIVE_VHOST}"
    sed -i "s|return[[:space:]]*301[[:space:]]*https://;|return 301 https://${DOMAIN}\$request_uri;|g" "${ACTIVE_VHOST}"
    
    print_success "Redirect pattern updated to: return 301 https://${DOMAIN}\$request_uri;"
}

# ==============================================================================
# 5. Remove Stray Backticks
# ==============================================================================

remove_stray_backticks() {
    print_section "5. REMOVE STRAY BACKTICKS FROM NGINX CONFIGS"
    
    print_step "Scanning for backticks in Nginx configuration files..."
    
    BACKTICK_COUNT=0
    
    # Search for backticks in all .conf files
    while IFS= read -r conf_file; do
        if grep -q '`' "$conf_file"; then
            print_warning "Found backticks in: ${conf_file}"
            
            # Backup before modification
            cp "${conf_file}" "${conf_file}.backup.$(date +%Y%m%d_%H%M%S)"
            
            # Remove backticks
            sed -i 's/`//g' "$conf_file"
            
            ((BACKTICK_COUNT++))
            print_success "Removed backticks from: ${conf_file}"
        fi
    done < <(find "${NGINX_CONF_DIR}" -type f -name "*.conf")
    
    if [[ $BACKTICK_COUNT -eq 0 ]]; then
        print_success "No stray backticks found"
    else
        print_success "Cleaned backticks from ${BACKTICK_COUNT} file(s)"
    fi
}

# ==============================================================================
# 6. Validate and Reload Nginx
# ==============================================================================

validate_and_reload_nginx() {
    print_section "6. VALIDATE AND RELOAD NGINX"
    
    print_step "Testing Nginx configuration..."
    
    if nginx -t 2>&1 | grep -q "syntax is ok"; then
        print_success "Nginx configuration is valid"
    else
        print_error "Nginx configuration has errors:"
        nginx -t
        return 1
    fi
    
    print_step "Reloading Nginx..."
    
    if systemctl reload nginx 2>/dev/null || service nginx reload 2>/dev/null; then
        print_success "Nginx reloaded successfully"
    else
        print_error "Failed to reload Nginx"
        return 1
    fi
    
    # Give Nginx a moment to fully reload
    sleep 2
    
    print_success "Nginx is running with new configuration"
}

# ==============================================================================
# 7. Verify Results
# ==============================================================================

verify_results() {
    print_section "7. VERIFY RESULTS"
    
    print_step "Checking HTTP→HTTPS redirect..."
    
    # Test HTTP redirect (if curl is available)
    if command -v curl &> /dev/null; then
        REDIRECT_TEST=$(curl -s -I "http://${DOMAIN}/" 2>/dev/null | grep -i "location:" | head -1)
        
        if echo "$REDIRECT_TEST" | grep -q "https://${DOMAIN}"; then
            print_success "HTTP redirects correctly to HTTPS"
            print_info "Redirect: ${REDIRECT_TEST}"
        else
            print_warning "Could not verify redirect (this may be normal if testing locally)"
            print_info "Expected: Location: https://${DOMAIN}/"
        fi
    else
        print_warning "curl not found, skipping redirect check"
    fi
    
    print_step "Checking security headers..."
    
    # Test security headers (if curl is available)
    if command -v curl &> /dev/null; then
        HEADERS=$(curl -s -I -k "https://${DOMAIN}/" 2>/dev/null || curl -s -I "http://localhost/" 2>/dev/null)
        
        # Check for each security header
        if echo "$HEADERS" | grep -qi "Strict-Transport-Security"; then
            print_success "HSTS header present"
        else
            print_warning "HSTS header not detected"
        fi
        
        if echo "$HEADERS" | grep -qi "Content-Security-Policy"; then
            print_success "CSP header present"
        else
            print_warning "CSP header not detected"
        fi
        
        if echo "$HEADERS" | grep -qi "X-Content-Type-Options"; then
            print_success "X-Content-Type-Options header present"
        else
            print_warning "X-Content-Type-Options header not detected"
        fi
        
        if echo "$HEADERS" | grep -qi "X-Frame-Options"; then
            print_success "X-Frame-Options header present"
        else
            print_warning "X-Frame-Options header not detected"
        fi
        
        if echo "$HEADERS" | grep -qi "Referrer-Policy"; then
            print_success "Referrer-Policy header present"
        else
            print_warning "Referrer-Policy header not detected"
        fi
    else
        print_warning "curl not found, skipping header checks"
    fi
    
    print_step "Configuration files created/modified:"
    print_info "Security headers: ${SECURITY_HEADERS_CONF}"
    if [[ -n "$ACTIVE_VHOST" ]]; then
        print_info "Vhost configuration: ${ACTIVE_VHOST}"
    fi
}

# ==============================================================================
# Main Execution
# ==============================================================================

main() {
    print_header
    
    # Execute all steps
    verify_root
    create_security_headers
    ensure_confd_inclusion
    fix_https_redirect
    remove_stray_backticks
    validate_and_reload_nginx
    verify_results
    
    # Final summary
    print_section "✅ SETUP COMPLETE"
    echo ""
    echo -e "${GREEN}Nginx security headers and redirect have been configured!${NC}"
    echo ""
    echo -e "${CYAN}What was done:${NC}"
    echo -e "  ${GREEN}✓${NC} Security headers added to ${SECURITY_HEADERS_CONF}"
    echo -e "  ${GREEN}✓${NC} conf.d/*.conf inclusion verified in nginx.conf"
    echo -e "  ${GREEN}✓${NC} HTTP→HTTPS redirect fixed to https://${DOMAIN}\$request_uri"
    echo -e "  ${GREEN}✓${NC} Stray backticks removed from configs"
    echo -e "  ${GREEN}✓${NC} Nginx validated and reloaded"
    echo ""
    echo -e "${CYAN}Next steps:${NC}"
    echo -e "  1. Test your site: ${BLUE}https://${DOMAIN}/${NC}"
    echo -e "  2. Verify headers: ${BLUE}curl -I https://${DOMAIN}/${NC}"
    echo -e "  3. Check redirect: ${BLUE}curl -I http://${DOMAIN}/${NC}"
    echo ""
}

# Run main function
main "$@"
