#!/bin/bash
# ==============================================================================
# Nexus COS - VPS Nginx Fix One-Liner Script
# ==============================================================================
# Purpose: Comprehensive one-liner for fixing Nginx issues on VPS server
# - Removes duplicate server_name entries
# - Strips backticks from CSP and Location headers
# - Ensures single source of truth for security headers
# - Fixes redirect patterns
# - Removes duplicate configs
# ==============================================================================
# Usage: sudo bash scripts/vps-nginx-fix-one-liner.sh
#        Or copy the command in the ONE_LINER variable below
# ==============================================================================

set -e

# The comprehensive one-liner that can be executed directly on VPS
ONE_LINER='sudo bash -c '\''set -e
DOMAIN=nexuscos.online

# Write clean security headers (single source of truth)
cat >/etc/nginx/conf.d/zz-security-headers.conf <<'"'"'EOF'"'"'
# Nexus COS Security Headers
# Generated by VPS Nginx Fix One-Liner

# HSTS (HTTP Strict Transport Security)
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

# Content Security Policy
add_header Content-Security-Policy "default-src '\''self'\'' https://nexuscos.online; img-src '\''self'\'' data: blob: https://nexuscos.online; script-src '\''self'\'' '\''unsafe-inline'\'' https://nexuscos.online; style-src '\''self'\'' '\''unsafe-inline'\'' https://nexuscos.online; connect-src '\''self'\'' https://nexuscos.online https://nexuscos.online/streaming wss://nexuscos.online ws://nexuscos.online;" always;

# X-Content-Type-Options
add_header X-Content-Type-Options "nosniff" always;

# X-Frame-Options
add_header X-Frame-Options "SAMEORIGIN" always;

# Referrer-Policy
add_header Referrer-Policy "no-referrer-when-downgrade" always;

# X-XSS-Protection (Legacy)
add_header X-XSS-Protection "1; mode=block" always;
EOF

# Ensure nginx.conf includes conf.d/*.conf
grep -q "conf.d/.*\.conf" /etc/nginx/nginx.conf || sed -i "/^http[[:space:]]*{/a \    include /etc/nginx/conf.d/*.conf;" /etc/nginx/nginx.conf

# Fix redirect in all vhosts and strip backticks + duplicate CSP lines
for ROOT in /etc/nginx /var/www/vhosts/system; do
  [ -d "$ROOT" ] || continue
  
  # Normalize redirect patterns for apex+www
  for VF in $(grep -RIl --include="*.conf" -E "server_name.*($DOMAIN|www\.$DOMAIN)" "$ROOT" 2>/dev/null || true); do
    # Fix redirect patterns
    sed -i "s|return[[:space:]]*301[[:space:]]*https://\$server_name\$request_uri;|return 301 https://\$host\$request_uri;|g" "$VF"
    sed -i "s|return[[:space:]]*301[[:space:]]*https://[a-zA-Z0-9.-]*\$request_uri;|return 301 https://\$host\$request_uri;|g" "$VF"
    sed -i "s|return[[:space:]]*301[[:space:]]*https://;|return 301 https://\$host\$request_uri;|g" "$VF"
    
    # Remove any CSP add_header from vhosts so only zz-security-headers.conf applies
    sed -i "/add_header[[:space:]]\+Content-Security-Policy/d" "$VF"
  done
  
  # Strip any stray backticks from all confs
  if command -v perl &> /dev/null; then
    find "$ROOT" -type f -name "*.conf" -print0 2>/dev/null | xargs -0 perl -0777 -pe "s/\x60//g" -i 2>/dev/null || true
  else
    find "$ROOT" -type f -name "*.conf" -exec sed -i "s/\`//g" {} \; 2>/dev/null || true
  fi
done

# If Plesk vhost exists, remove our redirect file to avoid duplicate server_name warnings
if ls /var/www/vhosts/system/"$DOMAIN"/conf/vhost_nginx.conf >/dev/null 2>&1 || \
   ls /var/www/vhosts/system/"$DOMAIN"/conf/nginx.conf >/dev/null 2>&1; then
  rm -f /etc/nginx/conf.d/zz-redirect.conf
fi

# Remove known duplicate gateway confs
rm -f /etc/nginx/conf.d/pf_gateway_${DOMAIN}.conf /etc/nginx/conf.d/pf_gateway_www.${DOMAIN}.conf

# Validate and reload
nginx -t && systemctl reload nginx

# Verify
echo "--- HTTPS HEADERS ---"
curl -fsSI "https://$DOMAIN/" 2>/dev/null | tr -d "\r" | egrep -i "^(Strict-Transport-Security|Content-Security-Policy|X-Content-Type-Options|X-Frame-Options|Referrer-Policy):" || echo "Could not fetch HTTPS headers (this is normal if testing locally)"

echo ""
echo "--- HTTP REDIRECT ---"
curl -fsSI "http://$DOMAIN/" 2>/dev/null | tr -d "\r" | egrep -i "^(HTTP|Location):" || echo "Could not fetch HTTP redirect (this is normal if testing locally)"

echo ""
echo "--- VERIFICATION COMPLETE ---"
echo "✓ Security headers configured in /etc/nginx/conf.d/zz-security-headers.conf"
echo "✓ Redirect patterns normalized to https://\$host\$request_uri"
echo "✓ Duplicate CSP headers removed from vhosts"
echo "✓ Backticks stripped from all configs"
echo "✓ Duplicate configs removed"
echo "✓ Nginx validated and reloaded"
'\''
'

# ==============================================================================
# Display the one-liner for easy copying
# ==============================================================================

echo "================================================================================"
echo "NEXUS COS - VPS NGINX FIX ONE-LINER"
echo "================================================================================"
echo ""
echo "This script contains a comprehensive one-liner that fixes:"
echo "  • Duplicate server_name entries on port 80"
echo "  • Backticks in CSP and Location headers"
echo "  • Redirect patterns (normalizes to https://\$host\$request_uri)"
echo "  • Duplicate CSP add_header lines"
echo "  • Duplicate gateway and redirect configs"
echo ""
echo "================================================================================"
echo "COPY AND RUN THIS COMMAND ON YOUR VPS:"
echo "================================================================================"
echo ""
echo "$ONE_LINER"
echo ""
echo "================================================================================"
echo "OR RUN THIS SCRIPT DIRECTLY:"
echo "================================================================================"
echo ""
echo "  sudo bash scripts/vps-nginx-fix-one-liner.sh --execute"
echo ""

# ==============================================================================
# Execute if --execute flag is provided
# ==============================================================================

if [[ "${1:-}" == "--execute" ]]; then
    echo "Executing one-liner fix..."
    echo ""
    eval "$ONE_LINER"
fi
