#!/bin/bash
# ==============================================================================
# Nexus COS - PF Gateway Fix Script for Apache Plesk
# ==============================================================================
# PF ID: SCAFFOLD_WIRE_NEXUS_COS_STACK
# Purpose: Configure Apache vhost includes for health endpoints and Socket.IO
# Usage: bash tools/pf_gateway_fix.sh
# ==============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ==============================================================================
# Utility Functions
# ==============================================================================

print_header() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                                                                ║${NC}"
    echo -e "${CYAN}║       NEXUS COS - PF GATEWAY FIX (APACHE PLESK)                ║${NC}"
    echo -e "${CYAN}║                                                                ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_step() {
    echo -e "${YELLOW}▶${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${CYAN}ℹ${NC} $1"
}

# ==============================================================================
# Configuration Variables
# ==============================================================================

# Domains from PF JSON
DOMAINS=("n3xuscos.online" "www.n3xuscos.online")

# ==============================================================================
# V-SUITE MODULE PORTS
# ==============================================================================
# V-Suite is the main module with sub-modules:
# - V-Screen Hollywood (port 3012)
# - V-Stage (port 3013)
# - V-Prompter Pro 10x10 (port 3017)
# - V-Caster Pro (port 3018)
# ==============================================================================
VSUITE_PORT="${PF_VSUITE_PORT:-3005}"
VSUITE_VSCREEN_HOLLYWOOD_PORT="${PF_VSCREEN_PORT:-3012}"
VSUITE_VSTAGE_PORT="${PF_VSTAGE_PORT:-3013}"
VSUITE_VPROMPTER_PRO_PORT="${PF_VPROMPTER_PORT:-3017}"
VSUITE_VCASTER_PRO_PORT="${PF_VCASTER_PORT:-3018}"
SOCKET_PORT="${PF_SOCKET_PORT:-3043}"

# Apache Plesk paths
PLESK_VHOST_CONF_DIR="/var/www/vhosts/system"
APACHE_CONF_INCLUDE="zz-health-sockets.conf"

# Fallback Apache paths
APACHE_CONF_AVAILABLE="/etc/apache2/conf-available"
APACHE_CONF_ENABLED="/etc/apache2/conf-enabled"

# ==============================================================================
# Detect Apache Configuration Directory
# ==============================================================================

detect_apache_config() {
    print_step "Detecting Apache configuration directory..."
    
    for domain in "${DOMAINS[@]}"; do
        if [[ -d "${PLESK_VHOST_CONF_DIR}/${domain}/conf" ]]; then
            APACHE_INCLUDE_DIR="${PLESK_VHOST_CONF_DIR}/${domain}/conf"
            print_success "Found Plesk vhost config: ${APACHE_INCLUDE_DIR}"
            return 0
        fi
    done
    
    # Fallback to standard Apache
    if [[ -d "${APACHE_CONF_AVAILABLE}" ]]; then
        APACHE_INCLUDE_DIR="${APACHE_CONF_AVAILABLE}"
        print_info "Using standard Apache conf-available: ${APACHE_INCLUDE_DIR}"
        return 0
    fi
    
    # Create local config directory
    APACHE_INCLUDE_DIR="$(pwd)/apache-includes"
    mkdir -p "${APACHE_INCLUDE_DIR}"
    print_info "Created local Apache includes directory: ${APACHE_INCLUDE_DIR}"
}

# ==============================================================================
# Generate Apache Health & Socket.IO Configuration
# ==============================================================================

generate_apache_config() {
    print_step "Generating Apache configuration for V-Suite and Socket.IO..."
    
    local config_file="${APACHE_INCLUDE_DIR}/${APACHE_CONF_INCLUDE}"
    
    cat > "${config_file}" << 'EOF'
# ==============================================================================
# Nexus COS - V-Suite & Socket.IO Proxy Configuration
# ==============================================================================
# Generated by: tools/pf_gateway_fix.sh
# PF ID: SCAFFOLD_WIRE_NEXUS_COS_STACK
# ==============================================================================
# V-Suite is the main Virtual Production module with sub-modules:
# - V-Screen Hollywood (port VSUITE_VSCREEN_HOLLYWOOD_PORT)
# - V-Stage (port VSUITE_VSTAGE_PORT)
# - V-Prompter Pro 10x10 (port VSUITE_VPROMPTER_PRO_PORT)
# - V-Caster Pro (port VSUITE_VCASTER_PRO_PORT)
# ==============================================================================

# Enable required Apache modules (ensure these are loaded)
# LoadModule proxy_module modules/mod_proxy.so
# LoadModule proxy_http_module modules/mod_proxy_http.so
# LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
# LoadModule rewrite_module modules/mod_rewrite.so

# ==============================================================================
# V-SUITE Health Endpoint Proxies
# ==============================================================================

# V-Suite Main Gateway Health
<Location "/api/v-suite/health">
    ProxyPass "http://127.0.0.1:VSUITE_PORT/health"
    ProxyPassReverse "http://127.0.0.1:VSUITE_PORT/health"
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
</Location>

# V-Suite/V-Screen Hollywood Health
<Location "/api/v-suite/vscreen-hollywood/health">
    ProxyPass "http://127.0.0.1:VSUITE_VSCREEN_HOLLYWOOD_PORT/health"
    ProxyPassReverse "http://127.0.0.1:VSUITE_VSCREEN_HOLLYWOOD_PORT/health"
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
</Location>

# V-Suite/V-Stage Health
<Location "/api/v-suite/vstage/health">
    ProxyPass "http://127.0.0.1:VSUITE_VSTAGE_PORT/health"
    ProxyPassReverse "http://127.0.0.1:VSUITE_VSTAGE_PORT/health"
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
</Location>

# V-Suite/V-Prompter Pro 10x10 Health
<Location "/api/v-suite/vprompter-pro/health">
    ProxyPass "http://127.0.0.1:VSUITE_VPROMPTER_PRO_PORT/health"
    ProxyPassReverse "http://127.0.0.1:VSUITE_VPROMPTER_PRO_PORT/health"
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
</Location>

# V-Suite/V-Caster Pro Health
<Location "/api/v-suite/vcaster-pro/health">
    ProxyPass "http://127.0.0.1:VSUITE_VCASTER_PRO_PORT/health"
    ProxyPassReverse "http://127.0.0.1:VSUITE_VCASTER_PRO_PORT/health"
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
</Location>

# ==============================================================================
# Socket.IO WebSocket Proxies with Upgrade Support
# ==============================================================================

# Primary Socket.IO endpoint: /socket.io -> http://127.0.0.1:SOCKET_PORT/socket.io
RewriteEngine On

# WebSocket upgrade for /socket.io
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/socket.io/(.*) ws://127.0.0.1:SOCKET_PORT/socket.io/$1 [P,L]

<Location "/socket.io">
    ProxyPass "http://127.0.0.1:SOCKET_PORT/socket.io"
    ProxyPassReverse "http://127.0.0.1:SOCKET_PORT/socket.io"
    ProxyPreserveHost On
    
    # WebSocket headers
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
    
    # Socket.IO long-polling support
    ProxyTimeout 86400
    ProxyBadHeader Ignore
</Location>

# Streaming Socket.IO mirror: /streaming/socket.io -> http://127.0.0.1:SOCKET_PORT/socket.io
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/streaming/socket.io/(.*) ws://127.0.0.1:SOCKET_PORT/socket.io/$1 [P,L]

<Location "/streaming/socket.io">
    ProxyPass "http://127.0.0.1:SOCKET_PORT/socket.io"
    ProxyPassReverse "http://127.0.0.1:SOCKET_PORT/socket.io"
    ProxyPreserveHost On
    
    # WebSocket headers
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Real-IP "%{REMOTE_ADDR}s"
    
    # Socket.IO long-polling support
    ProxyTimeout 86400
    ProxyBadHeader Ignore
</Location>

# ==============================================================================
# End of Nexus COS V-Suite & Socket.IO Configuration
# ==============================================================================
EOF

    # Replace port placeholders with actual values
    sed -i "s/VSUITE_PORT/${VSUITE_PORT}/g" "${config_file}"
    sed -i "s/VSUITE_VSCREEN_HOLLYWOOD_PORT/${VSUITE_VSCREEN_HOLLYWOOD_PORT}/g" "${config_file}"
    sed -i "s/VSUITE_VSTAGE_PORT/${VSUITE_VSTAGE_PORT}/g" "${config_file}"
    sed -i "s/VSUITE_VPROMPTER_PRO_PORT/${VSUITE_VPROMPTER_PRO_PORT}/g" "${config_file}"
    sed -i "s/VSUITE_VCASTER_PRO_PORT/${VSUITE_VCASTER_PRO_PORT}/g" "${config_file}"
    sed -i "s/SOCKET_PORT/${SOCKET_PORT}/g" "${config_file}"
    
    print_success "Generated Apache config: ${config_file}"
}

# ==============================================================================
# Enable Apache Configuration
# ==============================================================================

enable_apache_config() {
    print_step "Enabling Apache configuration..."
    
    # For standard Apache (non-Plesk)
    if [[ "${APACHE_INCLUDE_DIR}" == "${APACHE_CONF_AVAILABLE}" ]]; then
        if [[ ! -L "${APACHE_CONF_ENABLED}/${APACHE_CONF_INCLUDE}" ]]; then
            ln -sf "${APACHE_CONF_AVAILABLE}/${APACHE_CONF_INCLUDE}" "${APACHE_CONF_ENABLED}/${APACHE_CONF_INCLUDE}"
            print_success "Enabled Apache configuration via symlink"
        else
            print_info "Apache configuration already enabled"
        fi
    else
        print_info "Plesk will automatically include vhost configurations"
    fi
}

# ==============================================================================
# Test Apache Configuration
# ==============================================================================

test_apache_config() {
    print_step "Testing Apache configuration..."
    
    if command -v apachectl &> /dev/null; then
        if apachectl configtest 2>&1; then
            print_success "Apache configuration test passed"
            return 0
        else
            print_error "Apache configuration test failed"
            return 1
        fi
    elif command -v apache2ctl &> /dev/null; then
        if apache2ctl configtest 2>&1; then
            print_success "Apache configuration test passed"
            return 0
        else
            print_error "Apache configuration test failed"
            return 1
        fi
    else
        print_info "Apache control not found - skipping config test"
        return 0
    fi
}

# ==============================================================================
# Reload Apache
# ==============================================================================

reload_apache() {
    print_step "Reloading Apache..."
    
    if command -v systemctl &> /dev/null; then
        if systemctl is-active --quiet apache2 2>/dev/null; then
            systemctl reload apache2
            print_success "Apache2 reloaded via systemctl"
            return 0
        elif systemctl is-active --quiet httpd 2>/dev/null; then
            systemctl reload httpd
            print_success "HTTPD reloaded via systemctl"
            return 0
        fi
    fi
    
    if command -v service &> /dev/null; then
        if service apache2 status &>/dev/null; then
            service apache2 reload
            print_success "Apache2 reloaded via service"
            return 0
        elif service httpd status &>/dev/null; then
            service httpd reload
            print_success "HTTPD reloaded via service"
            return 0
        fi
    fi
    
    print_info "Apache not running or reload not available - manual reload required"
    return 0
}

# ==============================================================================
# Verify Health Endpoints
# ==============================================================================

verify_internal_health() {
    print_step "Verifying V-Suite internal health endpoints..."
    
    local endpoints=(
        "http://127.0.0.1:${VSUITE_PORT}/health"
        "http://127.0.0.1:${VSUITE_VSCREEN_HOLLYWOOD_PORT}/health"
        "http://127.0.0.1:${VSUITE_VSTAGE_PORT}/health"
        "http://127.0.0.1:${VSUITE_VPROMPTER_PRO_PORT}/health"
        "http://127.0.0.1:${VSUITE_VCASTER_PRO_PORT}/health"
        "http://127.0.0.1:${SOCKET_PORT}/health"
    )
    
    local all_ok=true
    
    for url in "${endpoints[@]}"; do
        if command -v curl &> /dev/null; then
            local code
            code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "${url}" 2>/dev/null || echo "000")
            if [[ "${code}" == "200" ]]; then
                print_success "OK: ${url}"
            else
                print_error "FAILED(${code}): ${url}"
                all_ok=false
            fi
        else
            print_info "curl not available - skipping ${url}"
        fi
    done
    
    if [[ "${all_ok}" == "true" ]]; then
        print_success "All V-Suite internal health endpoints verified"
    else
        print_info "Some health endpoints failed - services may not be running yet"
    fi
}

# ==============================================================================
# Print Summary
# ==============================================================================

print_summary() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║           PF GATEWAY FIX COMPLETE                              ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${CYAN}Configuration:${NC}"
    echo -e "  • Apache Include: ${APACHE_INCLUDE_DIR}/${APACHE_CONF_INCLUDE}"
    echo ""
    echo -e "${CYAN}V-SUITE MODULE (Main Virtual Production Suite):${NC}"
    echo -e "  • V-Suite Gateway:           Port ${VSUITE_PORT}"
    echo -e "  • V-Screen Hollywood:        Port ${VSUITE_VSCREEN_HOLLYWOOD_PORT} (sub-module)"
    echo -e "  • V-Stage:                   Port ${VSUITE_VSTAGE_PORT} (sub-module)"
    echo -e "  • V-Prompter Pro 10x10:      Port ${VSUITE_VPROMPTER_PRO_PORT} (sub-module)"
    echo -e "  • V-Caster Pro:              Port ${VSUITE_VCASTER_PRO_PORT} (sub-module)"
    echo ""
    echo -e "${CYAN}Health Endpoints:${NC}"
    echo -e "  • /api/v-suite/health                    -> http://127.0.0.1:${VSUITE_PORT}/health"
    echo -e "  • /api/v-suite/vscreen-hollywood/health  -> http://127.0.0.1:${VSUITE_VSCREEN_HOLLYWOOD_PORT}/health"
    echo -e "  • /api/v-suite/vstage/health             -> http://127.0.0.1:${VSUITE_VSTAGE_PORT}/health"
    echo -e "  • /api/v-suite/vprompter-pro/health      -> http://127.0.0.1:${VSUITE_VPROMPTER_PRO_PORT}/health"
    echo -e "  • /api/v-suite/vcaster-pro/health        -> http://127.0.0.1:${VSUITE_VCASTER_PRO_PORT}/health"
    echo ""
    echo -e "${CYAN}Socket.IO Endpoints:${NC}"
    echo -e "  • /socket.io           -> http://127.0.0.1:${SOCKET_PORT}/socket.io (ws_upgrade: true)"
    echo -e "  • /streaming/socket.io -> http://127.0.0.1:${SOCKET_PORT}/socket.io (ws_upgrade: true)"
    echo ""
    echo -e "${CYAN}Domains:${NC}"
    for domain in "${DOMAINS[@]}"; do
        echo -e "  • https://${domain}"
    done
    echo ""
    echo -e "${CYAN}Verification Commands:${NC}"
    echo -e "  # V-Suite health check:"
    echo -e "  for D in n3xuscos.online www.n3xuscos.online; do"
    echo -e "    for P in /api/v-suite/health /api/v-suite/vscreen-hollywood/health /api/v-suite/vstage/health /api/v-suite/vprompter-pro/health /api/v-suite/vcaster-pro/health; do"
    echo -e "      curl -sk -o /dev/null -w \"\$D\$P:%{http_code}\\n\" https://\$D\$P"
    echo -e "    done"
    echo -e "  done"
    echo ""
    echo -e "  # Socket.IO check:"
    echo -e "  for D in n3xuscos.online www.n3xuscos.online; do"
    echo -e "    for S in '/socket.io/?EIO=4&transport=polling' '/streaming/socket.io/?EIO=4&transport=polling'; do"
    echo -e "      curl -sk \"https://\$D\$S\" | grep -qo '\"sid\":\"' && echo \"\$D\$S: sid=true\" || echo \"\$D\$S: sid=false\""
    echo -e "    done"
    echo -e "  done"
    echo ""
}

# ==============================================================================
# Main Execution
# ==============================================================================

main() {
    print_header
    detect_apache_config
    generate_apache_config
    enable_apache_config
    test_apache_config
    reload_apache
    verify_internal_health
    print_summary
    
    echo -e "${GREEN}✨ PF Gateway Fix Complete! ✨${NC}"
}

# Run main function
main "$@"
