apiVersion: v1
kind: ConfigMap
metadata:
  name: trae-solo-config
  namespace: default
data:
  services.yaml: |
    services:
      - name: nexus-cos-frontend
        type: web
        port: 3000
        replicas: 2
        health_check: /health
        
      - name: nexus-cos-admin
        type: web
        port: 3001
        replicas: 1
        health_check: /health
        
      - name: nexus-cos-backend-node
        type: api
        port: 5000
        replicas: 2
        health_check: /api/health
        
      - name: nexus-cos-backend-python
        type: api
        port: 8000
        replicas: 2
        health_check: /health
        
      - name: nexus-cos-tv-radio
        type: media
        port: 8080
        replicas: 1
        health_check: /
        
      - name: nexus-cos-modules
        type: modules
        port: 9000
        replicas: 1
        health_check: /health
        
    routing:
      domain: nexuscos.online
      ssl: true
      paths:
        - path: /
          service: nexus-cos-frontend
        - path: /admin
          service: nexus-cos-admin
        - path: /api/v1
          service: nexus-cos-backend-node
        - path: /api/v2
          service: nexus-cos-backend-python
        - path: /tv
          service: nexus-cos-tv-radio
        - path: /modules
          service: nexus-cos-modules